Vagrant::Config.run do |config|
  config.vm.box = "precise64"

  config.vm.forward_port 80, 8080

  config.vm.provision :chef_solo do |chef|
    chef.add_recipe "build-essential"
    chef.add_recipe "wordpress"

    chef.json = {
      :wordpress => {
        :db => {
          :database => 'wp_database',
          :user => 'wp_dbuser',
          :password => '123456'
        }
      },
      :mysql => {
        :server_debian_password => '123456',
        :server_root_password => '123456',
        :server_repl_password => '123456'
      }
    }
  end
end
